# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef2976ca529e4eb1fc0aa0c88b99dc679c4441d6a9a5e25ffcf4792044eb4218fa5f788b90633217814d496744394c27099b5f05191bdb0d20a45e8584983936

test:
  secret_key_base: 9c8dce013773cdc1cc270c5505e7ae23bbf8e69481aef964c12fd2b616d3773a0405b504308c5b8a629dd0b39d99141b0847e43bc73d09d35a45906a13c54a72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
